#: pylint:skip-file
hotkeys:
  mod_key: ctrl

  clay_hotkeys:
    global:
      seek_start: mod + q
      play_pause: mod + p
      seek_backward: shift + left
      seek_forward: shift + right
      quit: mod + x
      toggle_shuffle: mod + r
      next_song: mod + d
      prev_song: mod + a
      toggle_repeat_one: mod + o
      handle_escape: esc, mod + _
      show_debug: meta + 0
      show_library: meta + 1
      show_artists: meta + 2
      show_stations: meta + 3
      show_playlists: meta + 4
      show_search: meta + 5
      show_queue: meta + 6
      show_settings: meta + 9

    song_item:
      activate: enter
      append: mod + a
      unappend: mod + u
      request_station: meta + s
      show_context_menu: meta + p
      thumbs_up: meta + u
      thumbs_down: meta + d
      clear_queue: meta + c

    song_view:
      move_to_beginning: home
      move_to_end: end
      move_up: up
      move_down: down
      hide_context_menu: meta + p

    general_page:
      activate: enter

    debug_page:
      copy_message: enter

    search_page:
      send_query: enter

    settings_page:
      equalizer_up: "+"
      equalizer_down: "-"

clay_settings:
  unicode: true
  player_class: clay.playback.vlc:VLCPlayer

play_settings:
  authtoken:
  device_id:
  download_tracks: false
  password:
  username:
